apiVersion: batch/v1
kind: Job
metadata:
  name: pinot-kafka-stream-job
spec:
  ttlSecondsAfterFinished: 20
  template:
    spec:
      containers:
      - name: pinot-kafka-stream-job
        image: node
        command: ["/bin/sh","-c"]
        args: 
          - mkdir /app; cd /app;
          - git pull https://github.com/volaka/pinot-kafka-stream-job.git; cd pinot-kafka-stream-job;
          - npm install; npm start;
          - echo Done;
      restartPolicy: Never
