apiVersion: batch/v1
kind: Job
metadata:
  name: pinot-kafka-stream-job
spec:
  ttlSecondsAfterFinished: 20
  template:
    spec:
      containers:
      - name: pinot-kafka-stream-job
        image: node
        command: ["/bin/sh","-c"]
        args: 
          - top
      restartPolicy: Never
